// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_content_delivery_bucket": "bluprnt-web-20200118223934-hostingbucket-bluprnt",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "https://d39vtqlj8rh84b.cloudfront.net"
};


export default awsmobile;
